# permissions for end users to view flashjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: flashjob-viewer-role
rules:
- apiGroups:
  - application.flashjob.nbfc.io
  resources:
  - flashjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.flashjob.nbfc.io
  resources:
  - flashjobs/status
  verbs:
  - get
