apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-controller-manager-rolebinding
subjects:
- kind: ServiceAccount
  name: operator-controller-manager
  namespace: operator-system
roleRef:
  kind: ClusterRole
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
