name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: harbor.nbfc.io
  REGISTRY_IMAGE: harbor.nbfc.io/cloud-iot/akri_operator

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Login to Harbor registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.REGISTRY_IMAGE }}:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true

      - name: Update Chart.yaml version
        run: |
          sed -i "s/version: .*/version: ${{ env.VERSION }}/" dist/chart/Chart.yaml

      - name: Update values.yaml with image tag
        run: |
          sed -i "s/tag: .*/tag: ${{ env.VERSION }}/" dist/chart/values.yaml

      - name: Package Helm chart
        run: |
          helm package dist/chart -d dist/helm-charts/charts

      - name: Upload Helm chart and install.yaml to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/helm-charts/charts/*.tgz
            dist/install.yaml
          tag_name: ${{ github.ref }}

      - name: Setup Helm repository
        run: |
          git config user.name "panosmaurikos"
          git config user.email "pmavrikos@nubificus.co.uk"
          git checkout -b gh-pages origin/gh-pages || git checkout --orphan gh-pages
          helm repo index dist/helm-charts/charts --url https://panosmaurikos.github.io/flashjob_operator/
          cp dist/helm-charts/charts/index.yaml .
          git add index.yaml
          git commit -m "Update Helm repository index"
          git push origin gh-pages
